version: '3'

services:

  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - redis

  redis:
    image: redis:7
    container_name: redis_app
    command: --port 5370
    expose:
      - 5370
